<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\SantaClaus.Delivery.Domain\SantaClaus.Delivery.Domain.csproj" />
    <ProjectReference Include="..\SantaClaus.Delivery.ReadModel\SantaClaus.Delivery.ReadModel.csproj" />
    <ProjectReference Include="..\SantaClaus.Delivery.SharedKernel\SantaClaus.Delivery.SharedKernel.csproj" />
    <ProjectReference Include="..\..\..\SantaClaus.Shared\SantaClaus.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.0" />
    <PackageReference Include="Muflone" Version="8.5.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
