<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Muflone" Version="8.5.0" />
    
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Muflone\Muflone.Transport.InMemory\Muflone.Transport.InMemory.csproj" />
  </ItemGroup>

</Project>
